### ISSUE TITLE
Windows: 'Continue' button grayed out when entering password for encrypted repository

### ISSUE THREAD

**Issue by hstehr** [hbons/SparkleShare#1315]
When trying to connect to an encrypted repository with the windows client, a dialog is shown to ask for the password. However, the 'Continue' button at the bottom remains grayed out, making it impossible to create the project. The only option is to cancel, which then causes a #1187.

![Screenshot](https://f.cloud.github.com/assets/849863/682646/fd7104e4-d9cb-11e2-8a1d-7710db816afb.png)

**Comment by ianchanning** [comment]
@hstehr you're work around from [2 Jul 2013](https://github.com/hbons/SparkleShare/issues/1315#issuecomment-20324484) still works well.

However it is **very dangerous**. If you enter the incorrect password then it re-encrypts all the content of your repo (which is encrypted) with a new password and commits it back to your repo. Effectively rendering all your files useless and meaning that you'd have to manually step back in git to when the files were encrypted with the correct key somehow and then try this again. Thankfully I tried this on a test repo first :)

A safer workaround, if you have a copy of the repo on a separate machine, is to copy the directory and the relevant `<folder>` element from `%APPDATA%\sparkleshare\config.xml` across manually.

**Comment by hbons** [comment]
I've reverted the the password input via STDIN a while back in master. Does that fix the issue? For some reason passing the password in this way (which is considered safer) doesn't work on Windows.

**Comment by ianchanning** [comment]
I was just in the process of trying to build master on Windows... :)

Now I remember you saying this in the issues about reverting STDIN - but I couldn't find the issue where you solved it.

**Comment by ianchanning** [comment]
I've built v1.5.0 and it does work again now. Would be very useful if you could release out 1.5.0 it has quite a few fixes in it.

**Comment by hbons** [comment]
@ianchanning Yes, we really need to make a release. Thanks for testing!

**Comment by Jabe** [comment]
@hstehr thanks for that awesome workaround! :smirk:

**Comment by haikarainen** [comment]
Hi, I still have this issue in Windows 10. Host is Ubuntu 15 (using dazzle), another client on my laptop is Ubuntu 15 as well (pretty much identical installs). The openssl spoof workaround worked for me (hopefully I entered the correct password lol).

# However...
I vote for scrapping the implementation of this completely, it is obviously very flawed (Both to bruteforce attacks, figuring out your password, and the openssl spoof possibly ruining your repo). Redo it and redo it correctly, and dont do checks continously as text is inputed. Do one check when you press "continue" and have it go back on fail up to 3 times and then put a cooldown of 5 minutes or so on the client ID.

**Comment by hbons** [comment]
@haikarainen I'd like to hear how this is vulnerable to attacks? I'm not a security expert, so any tips how to make it better would be appreciated. Limiting a number of attempts won't fix anything though, as it would be an artificial limitation put on top by the UI.

**Comment by haikarainen** [comment]
@hbons 

## First problem -- Ruining a repository

As pointed out by @ianchanning, spoofing the openssl executable with one that always returns true allows one to encrypt full repositories with your own password, basically taking control of it -- and even if no source data can be read, this scenario could be useful in extortion scenarios

## Second problem -- Bruteforce attacks

By hacking together something rather simple, you can bruteforce the UI by programatically entering a password in the textbox and then check if the continue button is disabled or not. This way you both gain access to the repository, as well as learning the actual password.

## Solution?

I am no security expert either, and I dont know how the underlying checks to see if the password is correct works, but it shouldn't be local, or bound by another executable like it is now. I understand that having a git backend introduces limitations on how you might implement security features, but I don't believe its impossible to improve what is currently had.

Maybe this is over-engineering things since we already have client ID's to authenticate, but I still feel that somehow the data should be decrypted on server, and then transmitted using some other client-specific encryption (SSL/TLS). This way the data is stored encrypted using a password only the host of  the repo knows, and the data is also transferred encrypted. This would however create a need for a sparkle-share specific implementation of a git ssh/https server (or extension of an already existing one).

That said, I really only want to point out the flaws by the system, and not provide actual solutions (as I'm not a security expert). The only things I could say right now that might improve it (if even by a little bit), is to:

1. Assert that the client ID  checks are done properly, not doing any sort of IPC or forking another process from an external executable.

2. Remove openssl.exe (and any other executable) as a dependency, and instead implement the functionality properly using statically linked libraries.

3. "Obfuscate" the UI from a pen-testing point of view by having the check being done once after you press continue (as opposed to doing it everytime you input a character in the textbox), as well as implementing a limiter.

This will not make it watertight, but it will raise the bar on what kind of skillset is needed to break this.

**Comment by hbons** [comment]
@haikarainen Don't both your points assume access to the client's computer, in which case an attacker could do anything they want anyway? Sorry, I don't get it.

**Comment by haikarainen** [comment]
@hbons Both my points assume access to a client which has a valid client ID in the host, nothing more.  I still think the issue is pretty big, the security of this system right now is pretty crap.

**Comment by hbons** [comment]
@haikarainen When you have access to a client computer you're at the mercy of the attacker and the battle is already lost. If you can replace openssl, you can also replace SparkleShare binaries with whatever malicious code.

**Comment by haikarainen** [comment]
@hbons You completely miss the issue at hand. You are partly correct with that damage has already been done, but your naivety with regards to the issue would also let the attacker completely ruin a repository on another server, to which he did not have access to and wouldn't really have access to without this very flawed "security".

Anyway as I'm seeing you will not do anything about this I will stop pushing you about it. Regards.

**Comment by markusstoll** [comment]
@haikarainen From my point of view the whole encryption feature was introduced to use an untrusted server as secure repository. So if you have to implement the security features in the client only, your measures to tighten client security are limited. (I dont want to advocate against improving the client in some aspects, just want to point out that there are obvious limitations)

**Comment by hbons** [comment]
@haikarainen I merely asked for clarification as I don't understand the issue. Calling me naive and claiming don't want to do anything about this is neither nice nor productive.

Ruining a remote repository will always be limited as Git keeps a history and force pushing can be disabled. SparkleShare is no different to using Git and OpenSSL command line tools, it just automates it.

@markusstoll is right, the assumption for this feature is that the client is secure and the server potentially untrusted.

**Comment by haikarainen** [comment]
@hbons  I think the issue here is how sparkleshare is marketed. Currently it's marketed as an easy to use, selfhosted cloud/sync service. In reailty it should maybe be marketed as complementary tools to git and openssl then? Because as it is now, sparkleshare is flawed in terms of being "the full package".

To quote the website
>How does it work?
>SparkleShare creates a special folder on your computer. You can add remotely hosted folders (or "projects") to this folder. These projects will be automatically kept in sync with both the host and all of your peers when someone adds, removes or edits a file.

This has given me the impression that the aim of SparkleShare is to provide it's end users with a full and complete cloud/sync service, which should of course include the full package (security etc.). Right now it sounds more like the aim of SparkleShare is to be a complementary tool along git and nothing else.  I understand how git/openssl currently limits certain functionality, but I also feel that you then use the completely wrong tools to begin with.

My intentions are not to offend you, but rather to be as concise and real as possible. That sometimes means to point out negative things.

Anyway, I no longer have any interest in this software because of unrelated events (something didnt sync correctly, sparkleshare crashed, repo ended up being useless, currently setting up gitlab with my backups instead).

I wish you good luck on this project and your future endeavours.

**Comment by ianchanning** [comment]
@haikarainen if you're intention is not to offend you certainly use very offensive language.

Please don't forget this is a free open source project maintained almost exclusively by @hbons in his spare time.

The worst thing would be if he gave up developing this because of unfair criticisms - which comments like yours will certainly push him to do.

Being able to encrypt a repo on your computer is a very useful feature. It is much more likely that you can trust the client and not the server. Neither Google Drive or Dropbox offer this feature - you have to install Boxcryptor or the like on top.

**Comment by haikarainen** [comment]
@ianchanning I honestly dont see how I'm using "very offensive language". I'm simply being real and I can't see how any criticism could be unfair given that the criticism actually points out factual flaws.  I guess we are all of different emotional sensitivities. Anyway what can be said about this issue has already been said, I have no interest in continuing this soap opera.

Again, good luck with your future endeavours, until next time :)

**Comment by hbons** [comment]
I wasn't offended. Thanks for the suggestions.

**Comment by toby-1-kenobi** [comment]
The two problems that @haikarainen mentions above do not require the black-hat to have access to the user's client machine. He merely needs the address of the repository. He can set up the client on his own machine.

If the black-hat doesn't know the user's encryption password, he can use a different password - SparkleShare wont dcrype the files for him, but will let him overwrite them and upload the the repository - in fact that will happen automatically when he puts a different password in. That's problem 2 listed above.

Problem 1 is related to the fact the SpakleShare dialogue when asking for the password only enables the continue button when the correct password is entered (is that really the behaviour? It seems very strange!) Again imagine black-hat setting up his own SparkleShare client, using the user's repository. He just needs to run a script in that dialogue window that keeps changing the content of the password box until it sees the continue button enabled. Then he has the user's password.

This is just to clarify @haikarainen's comments above. I don't know if these problems are real, but if they are then it seems like pretty serious security flaws.

**Comment by toby-1-kenobi** [comment]
My experience set out in issue #1696 seems to indicate that the problem of overwriting the content on the server by using a different password to the real one is a real problem.

@hbons please comment on the current state of this. I'm hoping for some reassurance because as far as I can see it's a really bad idea to use the client-side encryption feature as it is.

**Comment by toby-1-kenobi** [comment]
Oh, I've just remembered that black-hat's client needs to be linked to the server before it has access! Phew!

Still, issue #1696 is still a big problem

**Comment by hbons** [comment]
@toby-1-kenobi 
> Again imagine black-hat setting up his own SparkleShare client, using the user's repository. He just needs to run a script in that dialogue window that keeps changing the content of the password box until it sees the continue button enabled. Then he has the user's password.

This is a brute-forcing process, and can also be done by passing passwords to openssl. No SparkleShare client needed. Encryption isn't insecure because it can be brute-forced.

**Comment by hbons** [comment]
I'd like to add a comment to a point previously raised about ruining the repository and/or taking files hostage. This should not be possible, as long as force-pushing is not enabled on the host, you can always revert back to any point in Git's history. Data can only be added, not removed.
