### ISSUE TITLE
'Continue' button greyed out in encrypted share password entry step

### ISSUE THREAD

**Issue by skaag** [hbons/SparkleShare#1416]
I noticed a bug from a few months ago on the Windows platform, where the same behavior is described. I'm seeing the same thing here on the Mac platform. (the windows bug: https://github.com/hbons/SparkleShare/issues/1315)

Basically when trying to add an encrypted share, the wizard asks for a password. However the 'continue' button is disabled, and no matter what password I put into the field, it's still greyed out and I am unable to add the share.

**Comment by metaxmx** [comment]
Hi, I am experiencing the same problem, but with Windows7.
The (encrypted) repository was created with SparkleShare V1.2, now I have upgraded to SparkleShare 1.4 (newest).
All previously checked out projects are working fine, but when I want to add a new hosted project, I can't continue in the dialog where I have to enter the password (the button stays disabled).

I tried the workaround mentioned in the other bug report (https://github.com/hbons/SparkleShare/issues/1315#issuecomment-20324484) and I had no problems adding the hosted project (with all files decrypted correctly).

In the debug log I have multiple calls like this:

    16:04:58 | Cmd | Management-crypto | openssl enc -d -aes-256-cbc -base64 -pass stdin -in "D:\Share\.tmp\Management-crypto\.sparkleshare"
    16:04:58 | Cmd | Management-crypto | openssl enc -d -aes-256-cbc -base64 -pass stdin -in "D:\Share\.tmp\Management-crypto\.sparkleshare"
    16:04:58 | Cmd | Management-crypto | openssl enc -d -aes-256-cbc -base64 -pass stdin -in "D:\Share\.tmp\Management-crypto\.sparkleshare"
    16:04:59 | Cmd | Management-crypto | openssl enc -d -aes-256-cbc -base64 -pass stdin -in "D:\Share\.tmp\Management-crypto\.sparkleshare"
    16:04:59 | Cmd | Management-crypto | openssl enc -d -aes-256-cbc -base64 -pass stdin -in "D:\Share\.tmp\Management-crypto\.sparkleshare"

I have no special characters in the password (only [a-z]). When i manually call the printed openssl command in a cygwin shell, I get a decrypted hex-String when I entered the correct password (and an error message otherwise).

**Comment by ianchanning** [comment]
@metaxmx I too get the same output as you:

```
12:26:36 | Cmd | ian-crypto-test | openssl enc -d -aes-256-cbc -base64 -pass stdin -in "D:\SparkleShare\.tmp\ian-crypto-test\.sparkleshare"
12:26:36 | Cmd | ian-crypto-test | openssl enc -d -aes-256-cbc -base64 -pass stdin -in "D:\SparkleShare\.tmp\ian-crypto-test\.sparkleshare"
12:26:37 | Cmd | ian-crypto-test | openssl enc -d -aes-256-cbc -base64 -pass stdin -in "D:\SparkleShare\.tmp\ian-crypto-test\.sparkleshare"
12:26:37 | Cmd | ian-crypto-test | openssl enc -d -aes-256-cbc -base64 -pass stdin -in "D:\SparkleShare\.tmp\ian-crypto-test\.sparkleshare"
12:26:37 | Cmd | ian-crypto-test | openssl enc -d -aes-256-cbc -base64 -pass stdin -in "D:\SparkleShare\.tmp\ian-crypto-test\.sparkleshare"
12:26:38 | Cmd | ian-crypto-test | openssl enc -d -aes-256-cbc -base64 -pass stdin -in "D:\SparkleShare\.tmp\ian-crypto-test\.sparkleshare"
```

I assume that it tries re-running the command with each letter that you type until it gets a zero error response.

I could get the command working by using the correct password instead of `stdin` for the `-pass` argument, at least I think that is what should be returned. Here 'abcdef' is the correct password:

```
D:\SparkleShare\.tmp\ian-crypto-test>openssl enc -d -aes-256-cbc -base64 -pass pass:abcdef -in "D:\SparkleShare\.tmp\ian-crypto-test\.sparkleshare"
U2FsdGVkX19qu/8oqW1OIdAiIeGzJDLzDlrYZjYRjzKNgMLgAgkryT+KZylzQqrz
rWt2SYarcMCLA1DQCHN36f33Hwg1VkgP40nC5d4bUPXDR14DlWzR53PLkb5bVESI
mIyCEy10cw5jcKYjrtxBVrbuhtxWGRdq2BsTTEM5BVhfIxHgvRtsWMpTtQ8T0cQA
oziizJ4PM1xvZBUPd5EXSO6anC0/f1r1Ktl0x/xwGUshUrU5+ecPKoCso8VzRRtI
RA2uXcaA72QIFfo1x9FqKybd4b0aw4p12O91RWIGGuS4nWLi5iBqgzgqrdyY+/Tb
VD6Y9UGh6dL06+MZPo0XSNK91U3rwfcZAjdXkKo91ZE=
```

My only thought on this could be that I've got a separate msysgit installed (and in the `PATH`) - but that doesn't explain why it works with encrypting a new project but not an existing project

**Comment by hbons** [comment]
Should be fixed in master.
