### ISSUE TITLE
Read encryption password from STDIN

### ISSUE THREAD

**Issue by jgruiz75** [hbons/SparkleShare#1530]
OS: Windows 7 (x64)

Version 1.4 is unable to decrypt repositories as the continue button is always grayed out. 

Steps
1. Create a encrypted repository in a prior version (also seems to be a problem in current version per issue #1510 which was closed without really being resolved.). 
2. Use version 1.4 to clone repository. Unable to enter in password

Current Workaround
1. Use previous version (i.e. 1.2) to do the initial clone of the repositories

**Comment by hbons** [comment]
for new repositories we now hash the password and use that to encrypt. also, the password is read directly from its file, so it doesn't show up in process logs anymore.

**Comment by hbons** [comment]
we're back to reading the password from the file now. the password is also hashed and salted now, so reading from stdin is no longer needed / doesn't give any additional benefit.

**Comment by smilix** [comment]
Hi, I see there no newer Version since 1.4 (from April 2014). We have a crypted repository, the mac & linux clients work fine but the windows client fails. We can't complete the checkout because the continue button is always grey. I can't find the old 1.2 version (workaround from first post). What can I do?

**Comment by olegstepura** [comment]
Same here. 1.4. Windows. Continue is grey
