### ISSUE TITLE
SparkleShare on Android

### ISSUE THREAD

**Issue by janklostermann** [hbons/SparkleShare#1643]
Hello developers,

did someone already consider to port SparkleShare to Android?
Would be really useful to gain the capability to edit my notes in the git repository sync'd by Sparkleshare on the go on my tablet/phone.

Thanks for considering it. 
And looking forward to find it in the play store (even paying something for it).

**Comment by IvanMalison** [comment]
Wouldn't it really have to be a completely separate project? The issue is that sparkleshare seems to have been written in C# so none of the code could be used in an android application.

The good news is that since sparkleshare is basically just a wrapper around git, it shouldn't be TOO hard to acheive interoperability between two similarly constructed systems.

**Comment by hbons** [comment]
Due to lack of time SparkleShare's focus will be on desktop computers.

**Comment by janklostermann** [comment]
That's a pity, as thus it will not be able to help me. 
But I can understand the time issue and the need to focus... ;-)
