### ISSUE TITLE
Status icons on files

### ISSUE THREAD

**Issue by mcbridek** [hbons/SparkleShare#1712]
Hey! Great Tool. 

Just a few ideas, the dropbox screenshot explains most of them:
- Would be great to get visual feedback on files, (Syncing, Synced, Not Synced, File is open by someone else)? 
- Would also be nice to push sync + custom commit message? (Better for version control) 
- And also store some files on git and then choose to download. 

![dropbox](https://cloud.githubusercontent.com/assets/1561813/17168987/a121fd0a-53e5-11e6-9766-ef7579121f42.jpg)

**Comment by hbons** [comment]
This is hard to do reliably and in a way that is useful because of the way Git works (we can't know what files have changed on the server when downloading). I do want to show a list of your local changes that haven't synced yet wit hthe UI redesign #1774.

Your second suggestion is already possible by pausing the repo and then resuming it after making changes (it will ask for a commit message).

3rd will depend on the web UI you are using.

**Comment by ianchanning** [comment]
On Windows, if you install [Tortoise Git][1] then you get status icons for free in SparkleShare as it is just a Git repo. There might be something similar for Mac

[1]: https://tortoisegit.org/
