### ISSUE TITLE
Allow manual trigger of updates

### ISSUE THREAD

**Issue by jbuchbinder** [hbons/SparkleShare#794]
Before working in a disconnected state (for example, on an airplane), it would be useful to be able to "force" a sync with the remote server, to pull down any changes which are not present in the local repository.

I suggest adding another menu option to the tray, asking for all repos to be synchronized, effectively calling the appropriate Fetchers in sequence, potentially with a user notification to indicate completion.

**Comment by davelab6** [comment]
> If automatic syncs aren't happening, this is a bug. Having a "force update" action won't fix the bug.

I don't think that is true, because automatic sync's don't happen for all repos once per second. 

The pulling of updates isn't instant, and I've just experience a non-technical colleague complaining that SparkleShare hasn't synced down to their local computer the changes that I just pushed to the central git repo. 

What is the current tempo of checks for commits to pull down? 

I would like to be able to call for a sync from the main SparkleShare menu, without having to use an chord key to reveal it - my colleague would never think of this - and without having to restart which is a pain in the neck for rapid team collaboration.

**Comment by hbons** [comment]
the notification service is down at the moment, otherwise syncs would be
instant. it falls back to manual polling every 3 minutes.

**Comment by jmatsushita** [comment]
+1 for
> Alt modifier on the menu that changes "Add Remote Project..." to "Force Sync" 

Especially with the notification service down!

Thanks!

**Comment by hbons** [comment]
I redid the notifications, so that will be more stable pretty soon.
